<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Start typing_pulse-editor</name>
   <tag></tag>
   <elementGuidId>ee89e61d-6982-4ec8-a82d-64e6b1822d49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pulse-editor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pulse-editor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>00fd3bec-ab7c-4df2-9fc2-f5d609de9da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pulse-editor</value>
      <webElementGuid>0c4cd7ab-42f9-4b7f-8c91-889505f25a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bfefb28c-0a28-4927-bac5-fd5179f77423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datacomponent</name>
      <type>Main</type>
      <value>StyledTextInput</value>
      <webElementGuid>826bb28c-957c-4ad7-bef4-5180e106dcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datasourcefile</name>
      <type>Main</type>
      <value>StyledTextInput.js</value>
      <webElementGuid>446d0845-1d0a-476d-b776-24ec395db58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9364052d-5367-412f-b7fd-18b910483549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focusvisible-polyfill</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>de8dd1fe-1e0d-4fbf-943e-a24c53b24f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pulse-editor&quot;)</value>
      <webElementGuid>5b54f7c6-1881-4e00-87cf-649c3b6940e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pulse-editor']</value>
      <webElementGuid>122380e5-bf66-4603-9f05-0b9e405cdb30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-app']/div/div/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>4d7ad099-d43d-48c7-842f-57ff39f3c012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>56673403-dfd2-4a19-8f4e-0b6b7258ea0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pulse-editor']</value>
      <webElementGuid>a77d743e-92ac-4bed-a3ca-a6e51c550e82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
