<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Join  Sign In</name>
   <tag></tag>
   <elementGuidId>1d1550ef-d951-4f6d-ade4-d81594528508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.login-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;react-app&quot;]/div/div/div/div/div/div[2]/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>16e72aa3-164e-4e40-b58c-008bf56449f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-button</value>
      <webElementGuid>f1d5e9e7-d2e4-400b-bf90-1f4d6f8df32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Join / Sign In</value>
      <webElementGuid>e1b77f6a-6174-4f6e-8482-03c1be8c0e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pi-unification-header-main&quot;)/div[1]/nav[@class=&quot;universal-navbar&quot;]/div[2]/div[@class=&quot;profile-container&quot;]/div[@class=&quot;login-button&quot;]</value>
      <webElementGuid>be0d50db-6863-4b67-a858-9a0388d017c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pi-unification-header-main']/div/nav/div[2]/div[2]/div</value>
      <webElementGuid>6485a029-b39a-4773-9bc0-0f84d457da85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Service'])[1]/following::div[8]</value>
      <webElementGuid>0f53f87d-1f7b-4ef7-839e-fa28f51a4143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Enterprise Technology Software and Services with Confidence'])[1]/preceding::div[2]</value>
      <webElementGuid>d31b578c-c0b6-4a91-948d-44b9b663e4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[1]/preceding::div[2]</value>
      <webElementGuid>01c58fe6-3c3a-472e-b0d8-6b493d0812b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Join / Sign In']/parent::*</value>
      <webElementGuid>ff4d18ac-e927-4b8a-af3e-36a439ebe2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>2fb10545-1941-4e76-bfd4-27a6bb1cf845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Join / Sign In' or . = 'Join / Sign In')]</value>
      <webElementGuid>0ec0443c-d254-49fa-8023-89404318bddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
