<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log in with password instead</name>
   <tag></tag>
   <elementGuidId>e968cdcd-1df7-4c01-9472-da5b2b716fd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.uxdLink_uxdLinkPrimary__GPfsE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login_logInForm__1BIrf']/div[3]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9bbbed81-ca61-4cb5-b4e5-eada2180af3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>32c45f1f-df22-42e3-a1e4-3eea1a1b4179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>cb5d643a-6f9e-4d14-af86-fb785de5a2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uxdLink_uxdLinkPrimary__GPfsE</value>
      <webElementGuid>f86a6a2d-5e99-4822-8f99-e1cbe2e60775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interaction</name>
      <type>Main</type>
      <value>pi-user-app-login-with-password-link</value>
      <webElementGuid>0a79a260-c727-4746-8bb0-f6f275f2e555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-referrer</name>
      <type>Main</type>
      <value>Reviews</value>
      <webElementGuid>565c2e86-aea5-4b2a-b550-f70dac24c968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in with password instead</value>
      <webElementGuid>12114d92-ea9b-4953-b28d-1fdb4974cece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_logInForm__1BIrf&quot;)/div[@class=&quot;flex-row-wrap&quot;]/div[@class=&quot;flex-col-sm-6 login_loginMethodSwitch__3_JHa&quot;]/a[@class=&quot;uxdLink_uxdLinkPrimary__GPfsE&quot;]</value>
      <webElementGuid>c4d6043b-6df9-4833-8928-4cb338c0e30d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_logInForm__1BIrf']/div[3]/div/a</value>
      <webElementGuid>ae5f4a1c-bfed-4418-87b5-16c51db3ce9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log in with password instead')]</value>
      <webElementGuid>963b7e98-a67b-4113-ad50-33bbfc88031e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get passcode'])[1]/following::a[1]</value>
      <webElementGuid>5f48743c-7845-4981-9674-dbc9b45682ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::a[1]</value>
      <webElementGuid>e69a9b84-09fe-4292-8e21-81a84d3971b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/preceding::a[1]</value>
      <webElementGuid>3c9b7568-638f-4165-800d-9b9e2db01de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log in with password instead']/parent::*</value>
      <webElementGuid>a32e8423-f1dc-467c-b7a3-fcf6cb214062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>09cb40fa-91fc-4611-8bab-8d9baff6f64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>cbc99eea-f85b-4722-b83f-1dbb1c9e545b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Log in with password instead' or . = 'Log in with password instead')]</value>
      <webElementGuid>79e3d186-4547-4f8b-9dd2-f89fb46aeff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
