<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log in after pascode</name>
   <tag></tag>
   <elementGuidId>c5c9bed1-2730-4e0b-b10e-8dba5d9307dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.uxdButton_uxdBtnPrimary__flZrk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>190bc563-0ece-4611-a1e2-9208ec896bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uxdButton_uxdBtnPrimary__flZrk</value>
      <webElementGuid>2d30b9c3-4de0-4fa8-b140-eaa8d39f99f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4e571b68-d7cc-4655-9c7d-7b425dba4d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interaction</name>
      <type>Main</type>
      <value>pi-user-app-login-passcode-submit-button</value>
      <webElementGuid>b46c6c76-56d3-45df-b242-646b694e404d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-referrer</name>
      <type>Main</type>
      <value>Community</value>
      <webElementGuid>11475b68-a22f-4837-92bb-af1a6f537ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>8ee99261-a68b-43c3-bda4-57d8b758ed63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passcodeScreen_passcodeForm__2Fkez&quot;)/div[@class=&quot;passcodeScreen_passcodeButtons__29W0W flex-row-wrap&quot;]/div[@class=&quot;button flex-col-sm-6&quot;]/button[@class=&quot;uxdButton_uxdBtnPrimary__flZrk&quot;]</value>
      <webElementGuid>b84336c0-7816-4452-9655-28400f8d31b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>e95d9493-6fc6-4021-b45a-db59b133de08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='passcodeScreen_passcodeForm__2Fkez']/div[2]/div/button</value>
      <webElementGuid>561b7bc5-6932-4ecd-a31e-86371a39312e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passcode'])[1]/following::button[1]</value>
      <webElementGuid>308347be-5625-42ea-9549-327820703101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='salman.ahmad@ssidecisions.com.'])[1]/following::button[1]</value>
      <webElementGuid>aece6bd7-d5ae-4a1c-9820-4d9a75807147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community Guidelines'])[2]/preceding::button[1]</value>
      <webElementGuid>83f1e8d5-aefd-402d-9c5b-9231288b3b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log in']/parent::*</value>
      <webElementGuid>3ce73cd5-74ca-4816-bbfe-d1a9b3b8fbd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>265fff87-57a9-4954-90e4-63298afe1920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Log in' or . = 'Log in')]</value>
      <webElementGuid>c4878c50-03c1-4ce3-9cab-8e73b8baa5e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
