<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get passcode</name>
   <tag></tag>
   <elementGuidId>3cd191f4-ffcd-49d2-9b32-fb3510d955de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.uxdButton_uxdBtnPrimary__flZrk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cae50104-e380-44b8-9f74-329eba7ac2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uxdButton_uxdBtnPrimary__flZrk</value>
      <webElementGuid>16d11fde-e8bf-4eb0-ad5f-f48d239f5944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6a309028-76ec-4807-bdd6-0f0dec661c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interaction</name>
      <type>Main</type>
      <value>pi-user-app-get-login-passcode</value>
      <webElementGuid>8d4a3336-582a-491f-8e6b-25438cdec5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-referrer</name>
      <type>Main</type>
      <value>Community</value>
      <webElementGuid>a0d2ee8c-11c0-47c9-b71f-21db5a8698ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get passcode</value>
      <webElementGuid>517c3dc4-cdc1-465d-94ef-559f2965985a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_logInForm__1BIrf&quot;)/div[@class=&quot;flex-row-wrap&quot;]/div[@class=&quot;button flex-col-sm-6&quot;]/button[@class=&quot;uxdButton_uxdBtnPrimary__flZrk&quot;]</value>
      <webElementGuid>321747bc-b8fc-4785-b171-6ba93c4befb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>4f8941cc-fa3b-4a99-b882-aa2eccfc7578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_logInForm__1BIrf']/div[2]/div/button</value>
      <webElementGuid>f3c77786-8fa0-40e7-a839-cce0c6f3a271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::button[1]</value>
      <webElementGuid>58d0e8e7-79f1-4cee-9e87-ab6494666838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::button[1]</value>
      <webElementGuid>e6e209f6-cb2e-466c-9b14-e17e073946de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/preceding::button[1]</value>
      <webElementGuid>feda81cb-274c-46b5-9789-97b6a90ca9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get passcode']/parent::*</value>
      <webElementGuid>ba6e496e-6df0-4207-852e-3d20c87932d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>cac0bd8e-af3d-45cd-989e-a022b7b071cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Get passcode' or . = 'Get passcode')]</value>
      <webElementGuid>00638156-3b91-45a5-bfe2-e2c3e0d2b782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
