<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ask a question</name>
   <tag></tag>
   <elementGuidId>b768e297-e8f9-4fdc-99d0-18e432f0ed9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-901oao.r-cqee49.r-deyg0r.r-adyw6z.r-majxgm.r-7ptqe7.r-1ifxtd0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-app']/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7d9c834-3fc5-49b9-8ceb-862ed8920ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>TextAskAQuestion</value>
      <webElementGuid>66bd4d8c-90c7-4a72-b5b0-26e7a5e9e416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>4b72ba2a-b313-4b3f-9d23-8153e5231e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-cqee49 r-deyg0r r-adyw6z r-majxgm r-7ptqe7 r-1ifxtd0</value>
      <webElementGuid>f1de1cb7-b2f4-44af-be13-1e61b7f44744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ask a question</value>
      <webElementGuid>6fe9a8a5-cd01-488e-b80b-b3112eae21e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-app&quot;)/div[@class=&quot;css-1dbjc4n r-13awgt0 r-12vffkv&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-12vffkv&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-1niwhzg r-6koalj r-13awgt0 r-1pi2tsx r-bnwqim r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-1niwhzg r-13awgt0 r-1d2f490 r-u8s1d r-ipm5af&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-z2wwpe r-11yh6sk r-97e31f r-bv2aro r-hxflta r-10xqauy r-1xcajam&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-6koalj r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-16y2uox&quot;]/div[@class=&quot;css-1dbjc4n r-ubezar&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-901oao r-cqee49 r-deyg0r r-adyw6z r-majxgm r-7ptqe7 r-1ifxtd0&quot;]</value>
      <webElementGuid>66b760e5-d664-44e4-8756-96951ed33606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-app']/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>1aadae18-c5d3-4b8b-a767-6304cca6330b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engineering'])[1]/preceding::div[3]</value>
      <webElementGuid>1d7be531-552a-4308-ae36-86ab3e5b8006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ask a question']/parent::*</value>
      <webElementGuid>54c2126f-772f-4145-ba81-cdc6df315f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>32cb0c18-3ff8-47a3-8ca7-5139edfd5a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ask a question' or . = 'Ask a question')]</value>
      <webElementGuid>cc65617f-85c2-45fe-a9f3-cf1c58d6c79b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
