<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Investment  100 points (Balance 300 points)</name>
   <tag></tag>
   <elementGuidId>401ad879-b79e-44ca-9104-1b5c3f817104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-901oao.r-xudpm7.r-13awgt0.r-deyg0r</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-app']/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94b01ae3-8f09-4e5b-8870-e8b9f841d76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>CostText</value>
      <webElementGuid>e33171c4-09ae-4f4f-ac60-202d91fc4897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataelement</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>87ed038b-a361-4fdb-84af-a6b3470ef812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datacomponent</name>
      <type>Main</type>
      <value>CostText</value>
      <webElementGuid>08d24ed3-0e04-41ad-b2ab-7639dbeb1d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datasourcefile</name>
      <type>Main</type>
      <value>CostText.js</value>
      <webElementGuid>7837d154-b9ce-4ea0-a3a3-0c3ebe72b23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>5a1f7202-d18d-4ba0-a47b-83ebe3db4420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-xudpm7 r-13awgt0 r-deyg0r</value>
      <webElementGuid>7f1a0d14-f62d-4f20-a967-f6ec02f45c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Investment = 100 points (Balance: 300 points)</value>
      <webElementGuid>4b570781-a16f-4b08-aaa1-5e71d89482f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-app&quot;)/div[@class=&quot;css-1dbjc4n r-13awgt0 r-12vffkv&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-12vffkv&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-1niwhzg r-6koalj r-13awgt0 r-1pi2tsx r-bnwqim r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-1niwhzg r-13awgt0 r-1d2f490 r-u8s1d r-ipm5af&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-z2wwpe r-11yh6sk r-97e31f r-bv2aro r-hxflta r-10xqauy r-1xcajam&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-6koalj r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-16y2uox&quot;]/div[@class=&quot;css-1dbjc4n r-ubezar&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1ifxtd0&quot;]/div[@class=&quot;css-901oao r-xudpm7 r-13awgt0 r-deyg0r&quot;]</value>
      <webElementGuid>6d5d40e9-d747-4b7f-8494-dfb398f21227</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-app']/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div[2]/div</value>
      <webElementGuid>9e5be2c7-9d5b-41d4-ac80-09a287e0836e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ask a question'])[1]/following::div[2]</value>
      <webElementGuid>4a41298e-1a03-4fdc-a515-d748a25a8954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engineering'])[1]/preceding::div[1]</value>
      <webElementGuid>99f4a173-abb5-4f7d-a5c1-01a7b98f7f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div</value>
      <webElementGuid>3acca70c-318a-4fbb-bed6-3eaa5d06bb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Investment = 100 points (Balance: 300 points)' or . = 'Investment = 100 points (Balance: 300 points)')]</value>
      <webElementGuid>592fa82f-4263-46d9-8b94-e7f22ee0616c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
