<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Post Departments</name>
   <tag></tag>
   <elementGuidId>6d446e09-9526-443e-b3b0-8fbb9f5c180a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-1awozwy.r-rs99b7.r-18u37iz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-app']/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5d247492-925e-4934-9115-ddcb60215b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>DeptsEditor</value>
      <webElementGuid>038b3224-793a-4f0c-af1b-c19a91fba2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1dbjc4n r-1awozwy r-rs99b7 r-18u37iz</value>
      <webElementGuid>47522557-595f-46ad-bc44-1c624c530539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>f2385818-450a-48d6-b40b-fa85d80a78a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-app&quot;)/div[@class=&quot;css-1dbjc4n r-13awgt0 r-12vffkv&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-12vffkv&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-1niwhzg r-6koalj r-13awgt0 r-1pi2tsx r-bnwqim r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-1niwhzg r-13awgt0 r-1d2f490 r-u8s1d r-ipm5af&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-z2wwpe r-11yh6sk r-97e31f r-bv2aro r-hxflta r-10xqauy r-1xcajam&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-6koalj r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0 r-16y2uox&quot;]/div[@class=&quot;css-1dbjc4n r-ubezar&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;r-1loqt21 r-18u37iz r-1otgn73 r-1i6wzkk r-lrvibr css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-rs99b7 r-18u37iz&quot;]</value>
      <webElementGuid>1de79480-160c-4091-b199-00959df526f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-app']/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div[3]/div</value>
      <webElementGuid>746d7c6a-a545-46c2-ab85-69f5d4949ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ask a question'])[1]/following::div[4]</value>
      <webElementGuid>b7771e8c-9876-4b07-a939-00977b279339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start typing'])[1]/preceding::div[4]</value>
      <webElementGuid>2753f32c-0e21-48f3-9933-5560e803d051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/div</value>
      <webElementGuid>da2fd37c-46ef-4543-8b8e-7af2166e99d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'All' or . = 'All')]</value>
      <webElementGuid>115c6d21-c10a-4664-8739-88e71a76d603</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
